#######################################################################################
# Book settings
title                         : Health Data Reports
author                        : Jubayer Hossain
logo                          : 'logo.png'
email                         : contact.jubayerhossain@gmail.com
description: >-
  Health Data Journal 

execute:
  execute_notebooks           : cache


html:
  favicon                     : 'logo.png'
  home_page_in_navbar         : false
  use_edit_page_button        : false
  use_repository_button       : true
  use_issue_button            : true

repository:
  url                         : https://github.com/hossainlab/har/
  branch                      : master
  path_to_book                : book


launch_buttons:
  notebook_interface          : classic
  binderhub_url               : "https://mybinder.org"
  colab_url                   : "https://colab.research.google.com"
  thebe                       : true

# For Plotly and Cufflinks
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
